version: 2
registries:
  npm-flatt:
    type: npm-registry
    url: https://npm.flatt.tech/
    replaces-base: true
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    registries:
      - npm-flatt
