name: "github-actions-cache-cleaner"
author: "dev-hato Development Team"
description: "GitHub Actionsのキャッシュが7GB未満になるまで掃除するGitHub Actionsです。"
inputs:
  github-token: # id of input
    description: "GitHubのトークン。"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const {script} = require('${{ github.action_path }}/dist/clean-cache.js')
          await script(github, context)
