name: 'github-actions-cache-cleaner'
author: 'dev-hato Development Team'
description: 'GitHub Actionsのキャッシュが7GB未満になるまで掃除するGitHub Actionsです。'
inputs:
  github-token: # id of input
    description: 'GitHubのトークン。'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6.3.3
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const script = require(`${process.env.GITHUB_WORKSPACE}/scripts/action/clean-cache.js`)
          await script({github, context})
