name: "github-actions-cache-cleaner"
author: "dev-hato Development Team"
description: "GitHub Actionsのキャッシュが7GB未満になるまで掃除するGitHub Actionsです。"
inputs:
  github-token: # id of input
    description: "GitHubのトークン。"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const {script} = require('${{ github.action_path }}/dist/clean-cache.js')
          await script(github, context)
