---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/github-actions-cache-cleaner.yml
      - dist/**
      - action.yml
permissions: read-all
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
