---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/github-actions-cache-cleaner.yml
      - src/**
      - action.yml
permissions: read-all
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
