---
name: github-actions-cache-cleaner

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 21 * * *' # 06:00 JST
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/github-actions-cache-cleaner.yml
      - scripts/action/**
      - action.yml

jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
